backend:
  name: git-gateway
  repo: dcorn068/hugo-restaurant-tutorial
  branch: master # Branch to update (optional; defaults to master)

  media_folder: 'src/img/gallery' # where uploaded files go

  collections:
    - name: food
      label: 'Food Item' # Used in the UI, "New Post"
      folder: 'site/content/food' # where documents are stored
      create: true # Allow users to create new docs in this collection
      fields: # each document has these
        - { label: 'Name of Item', name: 'title', widget: 'string' }
        - {
            label: 'Supported Meals',
            name: 'categories',
            widget: 'list',
            default: ['lunch', 'dinner'],
          }
        - {
            label: 'Ingredients/Description',
            name: 'description',
            widget: 'text',
          }
        - {
            label: 'Type of Food',
            name: 'type',
            widget: 'string',
            default: 'raw bar',
          }
        - { label: 'Price', name: 'price', widget: 'string' }
